name: Update packages database

on:
  schedule:
    - cron:  '0 1 * * 1'

  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  update-packages-db:
    runs-on: ubuntu-latest

    # `Settings > Actions > General > Allow GH Actions to create and approve
    # PRs` must be enabled.
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Make packages database
        run: nix develop --accept-flake-config --impure --command make-packages-db

      - name: Build website
        run: nix develop --accept-flake-config --impure --command make-elm-site-prod

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "pkgs: automatic update of packages database"
          body: |
            Update packages database to the current version provided by Geospatial NIX.
          branch: update-packages-db-pr
          commit-message: "pkgs: automatic update of packages database"
          assignees: imincik
          reviewers: imincik
          delete-branch: true
