name: Update packages database

on:
  schedule:
    - cron:  '0 1 * * 1'

  workflow_dispatch:

env:
  NIX_CONFIG: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

jobs:
  update-packages-db:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25

      - name: Make packages database
        run: nix develop --accept-flake-config --impure --command make-packages-db

      - name: Build website
        run: nix develop --accept-flake-config --impure --command make-elm-site-prod

      - name: DEBUG
        run: echo "debug" > README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "pkgs: automatic update of packages database"
          body: |
            Update packages database to the current version used by Geospatial NIX.
          branch: update-packages-db-pr
          delete-branch: true
          commit-message: "pkgs: automatic update of packages database"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          assignees: imincik
          reviewers: imincik
          token: ${{ secrets.PACKAGES_AUTOUPDATE_TOKEN }}
